<Project>
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType Condition="'$(Configuration)' == 'Debug'">full</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Debug'">true</DebugSymbols>
    <Optimize Condition="'$(Configuration)' == 'Debug'">false</Optimize>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>
    <Deterministic>true</Deterministic>

    <RimWorldRoot Condition="'$(RimWorldRoot)' == '' and '$(RIMWORLD_DIR)' != ''">$(RIMWORLD_DIR)</RimWorldRoot>
    <RimWorldRoot Condition="'$(RimWorldRoot)' == ''">C:\Program Files (x86)\Steam\steamapps\common\RimWorld</RimWorldRoot>
    <RimWorldManaged>$(RimWorldRoot)\RimWorldWin64_Data\Managed</RimWorldManaged>
    <HarmonyDll Condition="'$(HarmonyDll)' == '' and '$(HARMONY_DLL)' != ''">$(HARMONY_DLL)</HarmonyDll>
    <HarmonyDll Condition="'$(HarmonyDll)' == ''">C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HarmonyDll>
  </PropertyGroup>
</Project>
