<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FoundingBonds</RootNamespace>
    <AssemblyName>FoundingBonds</AssemblyName>
    <OutputPath>..\1.6\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RimWorldManaged)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyDll)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
